import Link from "next/link";
import { ArrowLeft, CalendarClock, CheckCircle2, Mail, MessageCircleMore, Send, ShieldCheck, Users } from "lucide-react";
import { BrandLogo } from "@/components/brand/brand-logo";
import { ContactForm } from "./contact-form";
import styles from "./contact.module.css";
function Logo(){return <BrandLogo className={styles.logo}/>}
function HeroArt(){return <div className={styles.heroArt} aria-hidden="true"><div className={styles.circuit}/><div className={styles.chat}><MessageCircleMore/></div><div className={styles.mail}><Mail/></div><div className={styles.rings}/></div>}
const nextSteps = [[Mail,"We Receive Your Message","Your message is sent directly to our team at hello@nuvrixa.co.za"],[Users,"We Review & Understand","We review your enquiry and understand your goals."],[ArrowLeft,"We Get Back To You","We'll respond within one business day with the right information."],[CalendarClock,"Let's Build Something Great","Start a Business Discovery and explore the opportunity."]] as const;
export default function ContactPage(){return <main className={styles.page}><header className={styles.header}><Link href="/"><Logo/></Link><nav>{[["Home","/"],["Solutions","/solutions"],["Services","/services"],["Process","/process"],["Results","/results"],["Contact","/contact"]].map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</nav><Link className={styles.audit} href="/business-discovery">Start Business Discovery</Link></header><section className={styles.hero}><div><span>GET IN TOUCH</span><h1>We&apos;re Here To Help.<br/>Let&apos;s Build Smarter<br/><em>Together.</em></h1><p>Have a question, need more information or want to explore how Nuvrixa can help your business? Send us a message and our team will get back to you as soon as possible.</p><a className={styles.email} href="mailto:hello@nuvrixa.co.za"><i><Mail aria-hidden="true"/></i><span><b>Email us anytime</b>hello@nuvrixa.co.za</span></a></div><HeroArt/></section><section className={styles.body}><ContactForm/><aside><h2>What Happens Next?</h2>{nextSteps.map(([Icon,title,copy])=><article key={title}><i><Icon aria-hidden="true"/></i><div><h3>{title}</h3><p>{copy}</p></div></article>)}<div className={styles.safe}><i><ShieldCheck aria-hidden="true"/></i><h2>Your Information Is Safe</h2><p>We respect your privacy. Your information is used solely to respond to your enquiry and is never shared with third parties.</p><hr/><h3>Prefer email?</h3><p>Reach us directly at<br/><a href="mailto:hello@nuvrixa.co.za">hello@nuvrixa.co.za</a></p></div></aside></section><section className={styles.cta}><div className={styles.calendar}><div/><i><CheckCircle2 aria-hidden="true"/></i></div><div><h2>Ready To Transform <span>Your Business?</span></h2><p>Complete your Business Discovery so we can identify opportunities to save time, reduce costs and scale with intelligent systems.</p></div><div><Link className={styles.audit} href="/business-discovery">Start Business Discovery <Send aria-hidden="true"/></Link><p>Your progress is saved on this device.</p></div></section></main>}
