/* eslint-disable @next/next/no-html-link-for-pages */
import styles from "./audit.module.css";
import { AuditForm } from "./audit-form";
import { BrandLogo } from "@/components/brand/brand-logo";
function Logo(){return <BrandLogo className={styles.logo}/>}
function HeroArt(){return <div className={styles.heroArt}><div className={styles.platform}><i/><i/><i/></div><div className={styles.screen}><div><i/><i/><i/></div><main><article>▰<br/>▰</article><article className={styles.pie}/><article>▥<br/>▥</article><article>⌁<br/>▰</article><article>▰<br/>▰</article></main></div></div>}
export default function AuditPage(){return <main className={styles.page}><header className={styles.header}><a href="/"><Logo/></a><nav>{["Home","Solutions","Services","Process","Results"].map(x=><a href={x==="Home"?"/":`/${x.toLowerCase()}`} key={x}>{x}</a>)}</nav><a className={styles.audit} href="#form">Book Free 30-Minute Audit　→</a></header>
 <section className={styles.hero}><div><span>FREE 30-MINUTE AUTOMATION AUDIT</span><h1>Let’s Build Smarter<br/>Systems. <em>Together.</em></h1><p>Book your free 30-minute Automation Audit and discover how Nuvrixa can help you save time, reduce costs and scale with intelligent automation.</p><div className={styles.promises}>{[["◷","30 Minutes","Focused Session"],["%","100% Free","No Obligation"],["♢","Confidential","Your Information Is Safe"],["♢","Actionable Insights","Walk Away With Clarity"]].map(x=><article key={x[1]}><i>{x[0]}</i><b>{x[1]}</b><small>{x[2]}</small></article>)}</div></div><HeroArt/></section>
 <section className={styles.body} id="form"><AuditForm/><aside><h2>What You Get</h2>{[["⌕","Process Review","We’ll review your current processes and systems."],["▥","Opportunity Identification","We’ll identify high-impact automation opportunities."],["ϟ","Solution Roadmap","You’ll receive a tailored automation roadmap."],["◎","Quick Wins","We’ll share quick wins you can implement right away."]].map(x=><article key={x[1]}><i>{x[0]}</i><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}<hr/><h2>Our Proven 5-Step Process</h2>{[["⌕","1. Discover","Understand your business, challenges and goals."],["↗","2. Design","Design the right solution tailored to your needs."],["</>","3. Build","Build and integrate your solution with precision."],["♢","4. Deploy","Deploy, test and ensure everything works seamlessly."],["▥","5. Optimise","Continuously optimise and drive better results."]].map(x=><article className={styles.miniStep} key={x[1]}><i>{x[0]}</i><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</aside></section>
 <section className={styles.cta}><div className={styles.calendar}><div/><i>◷</i></div><div><h2>Ready To Transform Your Business?</h2><p>Your free 30-minute Automation Audit is the first step.<br/>Let’s build smarter systems that drive real impact.</p></div><div><a className={styles.audit} href="#form">▣　Book My 30-Minute Audit　→</a><p>Complete the form, then choose a time<br/>without leaving Nuvrixa.</p></div></section>
 <footer className={styles.footer}>{[["♙","100% Secure","Your data is protected"],["♢","No Obligation","Completely free"],["♧","Private & Confidential","Your information stays private"],["✓","Results Focused","Actionable outcomes"]].map(x=><article key={x[1]}><i>{x[0]}</i><div><b>{x[1]}</b><small>{x[2]}</small></div></article>)}</footer></main>}
