/* eslint-disable @next/next/no-html-link-for-pages */
import styles from "./privacy.module.css";
import { BrandLogo } from "@/components/brand/brand-logo";
const sections=[
 ["♙","1. Information We Collect","We collect personal and business information that you provide to us, such as your name, email address, company name, job title, phone number and any information you provide when booking a session, contacting us or using our services."],
 ["⚙","2. How We Use Your Information","We use the information we collect to provide, operate and improve our services, communicate with you, understand your needs, deliver customised solutions, send you updates, and comply with legal obligations."],
 ["⌯","3. Information We Share","We do not sell your personal information. We may share your information with trusted third-party service providers who assist us in operating our website, conducting our business or servicing you, under strict confidentiality obligations."],
 ["◎","4. International Data Transfers","As we work with clients globally, your information may be transferred to and processed in countries outside of your own. We take steps to ensure that appropriate safeguards are in place to protect your information."],
 ["♢","5. Data Security","We implement industry-standard technical and organisational measures to protect your personal information against unauthorised access, alteration, disclosure or destruction."],
 ["♙","6. Your Rights","Depending on your location, you may have the right to access, update, correct, delete or restrict the use of your personal information. You may also object to or withdraw consent for certain uses."],
 ["◔","7. Cookies & Tracking Technologies","We use cookies and similar technologies to enhance your experience, analyse site traffic and support our marketing efforts. You can manage your cookie preferences in your browser settings."],
 ["↗","8. Third-Party Links","Our website may contain links to third-party websites. We are not responsible for the privacy practices or content of those sites."],
 ["▤","9. Changes To This Policy","We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new policy on this page with an updated date."],
 ["✉","10. Contact Us","If you have any questions or concerns about this Privacy Policy or how we handle your information, please contact us using the details below."],
];
function Logo(){return <BrandLogo className={styles.logo}/>}
function ShieldArt(){return <div className={styles.shieldArt}><div className={styles.circuit}/><div className={styles.shield}><div className={styles.lock}><i/><b/></div></div><div className={styles.rings}/></div>}
export default function PrivacyPolicyPage(){return <main className={styles.page}>
 <header className={styles.header}><a href="/"><Logo/></a><nav>{["Home","Solutions","Services","Process","Results"].map(x=><a href={x==="Home"?"/":`/${x.toLowerCase()}`} key={x}>{x}</a>)}</nav><a className={styles.audit} href="/audit">Book Free 30-Minute Audit　→</a></header>
 <section className={styles.hero}><div><span>LEGAL</span><h1>Privacy <em>Policy</em></h1><p>Your privacy is important to us. This Privacy Policy explains how Nuvrixa collects, uses, discloses and protects your personal information when you visit our website or use our services.</p><div className={styles.date}>▣　Last updated: 20 May 2025　 |　 Effective date: 20 May 2025</div></div><ShieldArt/></section>
 <section className={styles.content}><div className={styles.policies}>{sections.map(([icon,title,copy],i)=><details id={`section-${i+1}`} open key={title}><summary><i className={i%2?styles.purple:styles.cyan}>{icon}</i><div><h2>{title}</h2><p>{copy}</p></div><b>⌄</b></summary></details>)}</div><aside><div className={styles.index}><h2>ON THIS PAGE</h2>{sections.map(([,title],i)=><a href={`#section-${i+1}`} key={title}>●　 {title}</a>)}</div><div className={styles.priority}><div>♙</div><h2>Your Privacy, Our Priority</h2><p>We are committed to protecting your personal information and being transparent about how it is used.</p><a href="mailto:hello@nuvrixa.co.za">If you have any questions, we’re here to help.</a></div></aside></section>
 <footer className={styles.footer}><div className={styles.footerGrid}><div><Logo/><p>AI-powered systems and automations that help businesses save time, reduce costs and scale with confidence.</p><div className={styles.social}>in　✉　𝕏</div></div><div><h3>SOLUTIONS</h3>{["Solutions","Chaos","Blueprint","Integrations","Portal"].map(x=><a href="/solutions" key={x}>{x}</a>)}</div><div><h3>COMPANY</h3>{["About","Process","Results","Services"].map(x=><a href={`/${x.toLowerCase()}`} key={x}>{x}</a>)}</div><div><h3>RESOURCES</h3><a href="#">FAQ</a><a href="/privacy-policy">Privacy Policy</a><a href="/terms">Terms of Service</a></div><div><h3>STAY UPDATED</h3><p>Get insights on AI, automation and business transformation.</p><form><label htmlFor="privacy-email">Email</label><input id="privacy-email" type="email" placeholder="Enter your email"/><button aria-label="Subscribe">→</button></form></div></div><div className={styles.bottom}><span>© 2025 Nuvrixa. All rights reserved.</span><span><a href="/privacy-policy">Privacy Policy</a>　 |　 <a href="/terms">Terms of Service</a></span><a href="mailto:hello@nuvrixa.co.za">hello@nuvrixa.co.za</a></div></footer>
 </main>}
