/* eslint-disable @next/next/no-html-link-for-pages */
import base from "../privacy-policy/privacy.module.css";
import styles from "./terms.module.css";
import { BrandLogo } from "@/components/brand/brand-logo";
const sections=[
 ["▤","1. Acceptance of Terms","By accessing our website or using our services, you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree, please do not use our website or services."],
 ["♧","2. About Nuvrixa","Nuvrixa provides AI-powered automation solutions, system development, integration services, consulting and related professional services to businesses worldwide."],
 ["◇","3. Services","We provide services as described on our website or in a written proposal or statement of work. The scope, deliverables, timelines and fees for each project will be agreed in writing."],
 ["$","4. Client Responsibilities","You agree to provide accurate, complete and timely information required for us to deliver our services. You are responsible for any decisions made based on the services and outputs we provide."],
 ["♢","5. Fees and Payment","Fees are as agreed in the proposal or contract. Unless otherwise stated, payment is due in accordance with the agreed payment terms. All fees are non-refundable unless stated otherwise in writing."],
 ["♙","6. Confidentiality","Both parties agree to keep confidential all non-public information disclosed during the engagement. This obligation survives the termination of the relationship."],
 ["↗","7. Intellectual Property","All intellectual property in our methodologies, frameworks, tools, templates and content remain the property of Nuvrixa. You receive a limited license to use deliverables as agreed for your internal business use only."],
 ["◎","8. Third-Party Services","Our services may use third-party tools and platforms. We are not responsible for the availability, accuracy or performance of third-party services."],
 ["⊗","9. Limitation of Liability","To the maximum extent permitted by law, Nuvrixa shall not be liable for any indirect, incidental, special or consequential damages arising out of or related to our services."],
 ["⚖","10. Termination","Either party may terminate an engagement with written notice if the other party materially breaches these Terms and fails to remedy the breach within 14 days."],
 ["▣","11. Governing Law","These Terms shall be governed by and construed in accordance with the laws of the Republic of South Africa, without regard to its conflict of law principles."],
 ["✉","12. Changes to These Terms","We may update these Terms from time to time. The latest version will always be available on this page with the updated date."],
];
function Logo(){return <BrandLogo className={base.logo}/>}
function DocumentArt(){return <div className={styles.art}><div className={styles.doc}><b>N</b><i/><i/><i/><i/><span>⌁　⌁</span><em>✓</em></div><div className={styles.rings}/><div className={styles.circuit}/></div>}
export default function TermsPage(){return <main className={base.page}>
 <header className={base.header}><a href="/"><Logo/></a><nav>{["Home","Solutions","Services","Process","Results"].map(x=><a href={x==="Home"?"/":`/${x.toLowerCase()}`} key={x}>{x}</a>)}</nav><a className={base.audit} href="/audit">Book Free 30-Minute Audit　→</a></header>
 <section className={base.hero}><div><span>LEGAL</span><h1 className={styles.title}>Terms &amp; <em>Conditions</em></h1><p>These Terms and Conditions govern your access to and use of the Nuvrixa website and our services. By accessing our website or engaging our services, you agree to be bound by these Terms.</p><div className={base.date}>▣　Last updated: 20 May 2025　 |　 ◎　Applies globally</div></div><DocumentArt/></section>
 <section className={base.content}><div className={base.policies}>{sections.map(([icon,title,copy],i)=><details id={`term-${i+1}`} open key={title}><summary><i className={i%2?base.purple:base.cyan}>{icon}</i><div><h2>{title}</h2><p>{copy}</p></div><b>⌄</b></summary></details>)}<p className={styles.contact}>If you have any questions about these Terms and Conditions, please <a href="mailto:hello@nuvrixa.co.za">contact us.</a></p></div><aside><div className={base.index}><h2>ON THIS PAGE</h2>{sections.map(([,title],i)=><a href={`#term-${i+1}`} key={title}>●　 {title}</a>)}</div><div className={styles.commitment}><div>♢</div><h2>Our Commitment</h2>{[["♙","Transparent","Clear terms and honest communication."],["♧","Fair","We believe in fair and respectful business relationships."],["♢","Secure","Your data, privacy and trust are important to us."],["◎","Global","Our terms apply to clients and projects worldwide."]].map(x=><article key={x[1]}><i>{x[0]}</i><p><b>{x[1]}</b><span>{x[2]}</span></p></article>)}<hr/><a href="mailto:hello@nuvrixa.co.za">Questions?<span>We’re here to help.</span>hello@nuvrixa.co.za</a></div></aside></section>
 <footer className={base.footer}><div className={base.footerGrid}><div><Logo/><p>AI-powered systems and automations that help businesses save time, reduce costs and scale with confidence.</p><div className={base.social}>in　✉　𝕏</div></div><div><h3>SOLUTIONS</h3>{["Solutions","Chaos","Blueprint","Integrations","Portal"].map(x=><a href="/solutions" key={x}>{x}</a>)}</div><div><h3>COMPANY</h3>{["About","Process","Results","Services"].map(x=><a href={`/${x.toLowerCase()}`} key={x}>{x}</a>)}</div><div><h3>RESOURCES</h3><a href="/faq">FAQ</a><a href="/privacy-policy">Privacy Policy</a><a href="/terms">Terms &amp; Conditions</a></div><div><h3>STAY UPDATED</h3><p>Get insights on AI, automation and business transformation.</p><form><label htmlFor="terms-email">Email</label><input id="terms-email" type="email" placeholder="Enter your email"/><button aria-label="Subscribe">→</button></form></div></div><div className={base.bottom}><span>© 2025 Nuvrixa. All rights reserved.</span><span><a href="/privacy-policy">Privacy Policy</a>　 |　 <a href="/terms">Terms &amp; Conditions</a></span><a href="mailto:hello@nuvrixa.co.za">hello@nuvrixa.co.za</a></div></footer>
 </main>}
