export type DiscoveryFieldType =
  | "text" | "email" | "tel" | "url" | "number" | "date"
  | "textarea" | "select" | "multiselect" | "yesno"
  | "departments" | "processes" | "tools" | "uploads" | "ranking" | "consent";

export type DiscoveryField = {
  key: string;
  label: string;
  type: DiscoveryFieldType;
  required?: boolean;
  helper?: string;
  options?: readonly string[];
  placeholder?: string;
};

export type DiscoverySection = {
  id: number;
  title: string;
  description: string;
  fields: readonly DiscoveryField[];
};

const yesNo = ["Yes", "No", "Unsure"] as const;
const employeeRanges = ["Just me", "2–5", "6–10", "11–25", "26–50", "51–100", "More than 100"] as const;

export const departmentOptions = ["Sales", "Marketing", "Customer service", "Operations", "Administration", "Finance", "Human resources", "Procurement", "Stock or inventory", "Logistics", "Project management", "Legal or compliance", "Management", "IT", "Other"] as const;
export const toolOptions = ["Microsoft Excel", "Google Sheets", "Microsoft Word", "Google Docs", "Email", "WhatsApp", "Google Drive", "OneDrive", "Dropbox", "Accounting software", "CRM", "Project management software", "Booking software", "Point-of-sale system", "Inventory software", "HR software", "Payroll software", "Custom software", "Paper files", "Physical registers", "None", "Other"] as const;

export const discoverySections: readonly DiscoverySection[] = [
  { id: 1, title: "Contact Information", description: "Tell us who we should work with throughout the assessment.", fields: [
    {key:"fullName",label:"Full name",type:"text",required:true},{key:"jobTitle",label:"Job title or role",type:"text",required:true},{key:"email",label:"Business email address",type:"email",required:true},{key:"phone",label:"Contact number",type:"tel",required:true},
    {key:"preferredContact",label:"Preferred contact method",type:"select",required:true,options:["Email","Phone call","Video meeting","WhatsApp"]},{key:"city",label:"City",type:"text",required:true},{key:"province",label:"Province or state",type:"text",required:true},{key:"country",label:"Country",type:"text",required:true},{key:"contactTime",label:"Best time to contact",type:"text"},{key:"website",label:"Business website",type:"url"},{key:"linkedin",label:"LinkedIn profile",type:"url",helper:"Optional"}
  ]},
  { id: 2, title: "Company Overview", description: "Give us a practical picture of the organisation, market and operating scale.", fields: [
    {key:"registeredName",label:"Registered business name",type:"text",required:true},{key:"tradingName",label:"Trading name",type:"text"},{key:"industry",label:"Industry",type:"text",required:true},{key:"yearEstablished",label:"Year established",type:"number"},{key:"employees",label:"Number of employees",type:"select",required:true,options:employeeRanges},{key:"locations",label:"Number of locations",type:"number"},{key:"productsServices",label:"Main products or services",type:"textarea",required:true},{key:"customerType",label:"Typical customer type",type:"textarea"},{key:"market",label:"Main geographic market",type:"text"},{key:"monthlyEnquiries",label:"Estimated monthly enquiry volume",type:"text"},{key:"monthlyTransactions",label:"Estimated monthly customer or transaction volume",type:"text"},{key:"operatingDescription",label:"Briefly describe how the business currently operates",type:"textarea",required:true}
  ]},
  { id: 3, title: "Business Goals", description: "Define the outcomes the proposed system should support.", fields: [
    {key:"topGoals",label:"What are the three most important goals for the next 12 months?",type:"textarea",required:true},{key:"automationGoals",label:"What would you like automation to help you achieve?",type:"textarea",required:true},{key:"sixMonthSuccess",label:"What would success look like six months after implementation?",type:"textarea",required:true},{key:"primaryOutcome",label:"Which outcome matters most?",type:"select",required:true,options:["Save time","Reduce costs","Increase revenue","Improve customer service","Reduce errors","Improve reporting","Improve staff productivity","Create better internal control","Scale without hiring immediately","Other"]}
  ]},
  { id: 4, title: "Departments and Team Structure", description: "Select every function that exists. Follow-up questions appear only for selected departments.", fields: [{key:"departments",label:"Departments or functions in the business",type:"departments",required:true}]},
  { id: 5, title: "Current Business Processes", description: "Document both digital and paper-based workflows. Add as many processes as needed.", fields: [{key:"processes",label:"Business processes",type:"processes",required:true}]},
  { id: 6, title: "Paper-Based Processes", description: "Help us understand non-digital work, physical hand-offs and paper-related risk.", fields: [
    {key:"handForms",label:"Which forms are completed by hand?",type:"textarea"},{key:"registers",label:"Which registers or logbooks are used?",type:"textarea"},{key:"printedDocuments",label:"Which documents are printed regularly?",type:"textarea"},{key:"physicalSignatures",label:"Which documents require physical signatures?",type:"textarea"},{key:"paperCaptured",label:"Which paper documents are later captured into a computer?",type:"textarea"},{key:"paperCapturer",label:"Who captures this information?",type:"text"},{key:"paperStorage",label:"Where are paper records stored?",type:"textarea"},{key:"paperSearch",label:"How are paper records searched or retrieved?",type:"textarea"},{key:"paperLoss",label:"Are paper documents ever lost, duplicated, damaged or incomplete?",type:"textarea"},{key:"documentTravel",label:"Must staff travel or move between locations to deliver documents?",type:"yesno",options:yesNo},{key:"paperFrustration",label:"Which paper process causes the most frustration?",type:"textarea"},{key:"paperRisk",label:"Which paper process creates the greatest business risk?",type:"textarea"},{key:"digitalOpenness",label:"Would the business consider digital forms, electronic approvals or digital signatures?",type:"yesno",options:yesNo},{key:"paperWorkflow",label:"Explain your paper workflows in your own words",type:"textarea",required:true}
  ]},
  { id: 7, title: "Customer Journey", description: "Trace the journey from first enquiry through payment, support and re-engagement.", fields: [
    {key:"customerChannels",label:"How do customers first find or contact the business?",type:"multiselect",required:true,options:["Website","Email","Phone","WhatsApp","Facebook","Instagram","LinkedIn","Walk-ins","Referrals","Online marketplace","Other"]},{key:"enquiryMethod",label:"How do customers make enquiries?",type:"textarea"},{key:"enquiryRecording",label:"How are enquiries recorded?",type:"textarea"},{key:"enquiryOwner",label:"Who follows up with new enquiries?",type:"text"},{key:"responseSpeed",label:"How quickly are enquiries normally answered?",type:"text"},{key:"quotationCreation",label:"How are quotations created?",type:"textarea"},{key:"quotationSending",label:"How are quotations sent?",type:"textarea"},{key:"quotationFollowup",label:"How are quotations followed up?",type:"textarea"},{key:"customerOnboarding",label:"How are customers onboarded?",type:"textarea"},{key:"customerStorage",label:"How are customer details stored?",type:"textarea"},{key:"appointmentManagement",label:"How are appointments or bookings managed?",type:"textarea"},{key:"paymentCollection",label:"How are payments collected?",type:"textarea"},{key:"invoiceSending",label:"How are invoices sent?",type:"textarea"},{key:"complaintHandling",label:"How are customer complaints handled?",type:"textarea"},{key:"feedbackCollection",label:"How is customer feedback collected?",type:"textarea"},{key:"customerReengagement",label:"How are inactive customers re-engaged?",type:"textarea"},{key:"lostLeads",label:"Where are leads commonly lost?",type:"textarea",required:true}
  ]},
  { id: 8, title: "Existing Tools and Systems", description: "Select current tools and describe how each one supports the business.", fields: [
    {key:"tools",label:"Tools currently used",type:"tools",required:true},{key:"disconnectedSystems",label:"Are employees using systems that do not communicate?",type:"yesno",options:yesNo},{key:"duplicateEntry",label:"Is the same information entered into multiple systems?",type:"yesno",options:yesNo},{key:"systemsKeep",label:"Which systems must be kept?",type:"textarea"},{key:"systemsReplace",label:"Which systems should be replaced?",type:"textarea"},{key:"providerRestrictions",label:"Are there contractual restrictions with existing providers?",type:"textarea"},{key:"internalIT",label:"Does the company have internal IT support?",type:"yesno",options:yesNo}
  ]},
  { id: 9, title: "Documents and Data", description: "Map high-volume documents, storage, access, reporting and compliance needs.", fields: [
    {key:"frequentDocuments",label:"Which documents are created most often?",type:"textarea"},{key:"approvalDocuments",label:"Which documents require approval?",type:"textarea"},{key:"customerDocuments",label:"Which documents are sent to customers?",type:"textarea"},{key:"receivedDocuments",label:"Which documents are received from customers?",type:"textarea"},{key:"regularReports",label:"Which reports are prepared regularly?",type:"textarea"},{key:"criticalSheets",label:"Which spreadsheets are business-critical?",type:"textarea"},{key:"documentStorage",label:"Where are documents stored?",type:"textarea"},{key:"documentAccess",label:"Who can access them?",type:"textarea"},{key:"namingConventions",label:"Are naming conventions used?",type:"yesno",options:yesNo},{key:"versionControl",label:"Are document versions difficult to control?",type:"yesno",options:yesNo},{key:"confidentialData",label:"Does the business handle confidential or personal information?",type:"yesno",options:yesNo},{key:"retention",label:"Does the business have document retention requirements?",type:"yesno",options:yesNo},{key:"auditTrails",label:"Does the business need audit trails?",type:"yesno",options:yesNo},{key:"compliance",label:"Does the business operate under specific compliance requirements?",type:"textarea"},{key:"uploads",label:"Supporting files",type:"uploads",helper:"Secure uploads require the documented storage integration."}
  ]},
  { id: 10, title: "Problems and Bottlenecks", description: "Quantify the operational friction and rank the five most important pain points.", fields: [
    {key:"timeTasks",label:"Which tasks consume the most staff time?",type:"textarea"},{key:"repetitiveTasks",label:"Which tasks are most repetitive?",type:"textarea"},{key:"errorTasks",label:"Where do errors occur most often?",type:"textarea"},{key:"complaintTasks",label:"Which tasks create customer complaints?",type:"textarea"},{key:"deadlineTasks",label:"Which tasks cause missed deadlines?",type:"textarea"},{key:"followupTasks",label:"Which tasks depend heavily on manual follow-up?",type:"textarea"},{key:"copyPasteTasks",label:"Which tasks require copying and pasting?",type:"textarea"},{key:"repeatEntryTasks",label:"Which tasks require repeated data entry?",type:"textarea"},{key:"slowReports",label:"Which reports take too long to prepare?",type:"textarea"},{key:"hardToFind",label:"Which information is difficult to find?",type:"textarea"},{key:"noAccountability",label:"Which processes lack accountability?",type:"textarea"},{key:"hardToMonitor",label:"Which processes are difficult to monitor?",type:"textarea"},{key:"growthBlocker",label:"What prevents the business from growing faster?",type:"textarea",required:true},{key:"inefficiencyCost",label:"What is the approximate cost of these inefficiencies?",type:"text"},{key:"unchangedRisk",label:"What would happen if the current process remained unchanged?",type:"textarea"},{key:"painRanking",label:"Rank your top five pain points",type:"ranking",required:true}
  ]},
  { id: 11, title: "Automation Opportunities", description: "Identify priorities, approval boundaries and the preferred level of automation.", fields: [
    {key:"automationAreas",label:"Areas you are interested in improving",type:"multiselect",required:true,options:["Lead capture","Lead qualification","Lead follow-up","Customer onboarding","Quotation generation","Proposal generation","Appointment booking","Customer support","WhatsApp communication","Email automation","Document generation","Document approvals","Digital forms","Reporting dashboards","Invoice processing","Payment reminders","Expense approvals","Staff onboarding","Leave requests","Recruitment","Project management","Task assignment","Inventory monitoring","Order processing","Supplier management","Complaint management","Customer feedback","Data entry","Data migration","AI assistants","Internal knowledge base","Other"]},{key:"priorityAreas",label:"Which three areas should be prioritised?",type:"textarea",required:true},{key:"noAutomation",label:"Are there tasks you do not want automated?",type:"textarea"},{key:"humanApproval",label:"Do you want human approval before actions are completed?",type:"yesno",options:yesNo},{key:"humanDecisions",label:"Which decisions must always remain with a person?",type:"textarea"},{key:"aiOpen",label:"Would you be open to AI-assisted processes?",type:"yesno",options:yesNo},{key:"automationComfort",label:"What level of automation feels comfortable?",type:"select",required:true,options:["Suggestions only","Automation with human approval","Mostly automated with exception handling","Fully automated where appropriate","Unsure and need guidance"]}
  ]},
  { id: 12, title: "Reporting and Management", description: "Describe current reporting effort and the information management needs faster.", fields: [
    {key:"reportsProduced",label:"Which reports are produced?",type:"textarea"},{key:"reportFrequency",label:"How often are they produced?",type:"text"},{key:"reportOwner",label:"Who prepares them?",type:"text"},{key:"reportTime",label:"How long do they take?",type:"text"},{key:"reportRecipients",label:"Who receives them?",type:"textarea"},{key:"managementNumbers",label:"Which numbers matter most to management?",type:"textarea"},{key:"missingInformation",label:"Which information does management struggle to access?",type:"textarea"},{key:"liveDashboard",label:"Would the client benefit from a live dashboard?",type:"yesno",options:yesNo},{key:"usefulAlerts",label:"Which alerts or notifications would be useful?",type:"textarea"},{key:"dataDecisions",label:"Which decisions should be supported by better data?",type:"textarea"}
  ]},
  { id: 13, title: "Security, Access and Compliance", description: "Capture operational requirements only. Final compliance decisions may require professional review.", fields: [
    {key:"personalInfo",label:"Does the business handle personal customer information?",type:"yesno",options:yesNo},{key:"sensitiveInfo",label:"Does it handle medical, legal, financial or other sensitive information?",type:"yesno",options:yesNo},{key:"accessLevels",label:"Are different staff access levels required?",type:"yesno",options:yesNo},{key:"approvalActions",label:"Should certain actions require approval?",type:"yesno",options:yesNo},{key:"securityAuditLogs",label:"Does the business require audit logs?",type:"yesno",options:yesNo},{key:"backups",label:"Does the business require backups?",type:"yesno",options:yesNo},{key:"privacyPolicy",label:"Does the business have a privacy policy?",type:"yesno",options:yesNo},{key:"dataRetention",label:"Does the business have data retention requirements?",type:"yesno",options:yesNo},{key:"multiCountry",label:"Does the business operate in more than one country?",type:"yesno",options:yesNo},{key:"regulations",label:"Are there industry-specific regulations?",type:"textarea"},{key:"dataLocation",label:"Are there restrictions on where data may be stored?",type:"textarea"},{key:"securityIncident",label:"Has the business experienced data loss or a security incident?",type:"textarea",helper:"Do not include passwords or confidential incident credentials."}
  ]},
  { id: 14, title: "Prototype Requirements", description: "Tell us what would make the first solution review useful and decision-ready.", fields: [
    {key:"prototypeDemo",label:"What would you like demonstrated during the first meeting?",type:"textarea",required:true},{key:"prototypeProcess",label:"Which process should the prototype focus on?",type:"textarea",required:true},{key:"meetingAttendees",label:"Who will attend the prototype meeting?",type:"textarea"},{key:"decisionMaker",label:"Who is the final decision-maker?",type:"text"},{key:"proceedCriteria",label:"What would convince the business to proceed?",type:"textarea"},{key:"essentialFeatures",label:"Which features are essential?",type:"textarea"},{key:"optionalFeatures",label:"Which features would be useful but not essential?",type:"textarea"},{key:"likedExamples",label:"Are there systems or experiences you like?",type:"textarea"},{key:"prototypeBranding",label:"Should any branding be reflected in the prototype?",type:"textarea"},{key:"prototypeData",label:"Should the prototype use sample or client-provided data?",type:"select",options:["Sample data","Client-provided, non-sensitive data","A combination","Unsure"]}
  ]},
  { id: 15, title: "Budget, Decision and Timeline", description: "Help us recommend a realistic scope. Smaller budgets are welcome and may suit a phased approach.", fields: [
    {key:"budgetAllocated",label:"Has a budget been allocated?",type:"yesno",options:yesNo},{key:"budgetRange",label:"Preferred budget range",type:"select",required:true,options:["Under R10,000","R10,000–R25,000","R25,001–R50,000","R50,001–R100,000","R100,001–R250,000","More than R250,000","Budget not yet determined","Prefer not to disclose"]},{key:"desiredStart",label:"Desired start date",type:"date"},{key:"desiredLaunch",label:"Desired launch date",type:"date"},{key:"urgent",label:"Is the project urgent?",type:"yesno",options:yesNo},{key:"deadlineDriver",label:"What is driving the deadline?",type:"textarea"},{key:"projectApprover",label:"Who approves the project?",type:"text"},{key:"otherProviders",label:"Are other service providers being considered?",type:"yesno",options:yesNo},{key:"decisionDate",label:"Expected decision date",type:"date"},{key:"phasedBuild",label:"Would you prefer a phased build?",type:"yesno",options:yesNo},{key:"supportPlan",label:"Would you consider an ongoing support plan after launch?",type:"yesno",options:yesNo}
  ]},
  { id: 16, title: "Final Review and Consent", description: "Review the assessment, edit any section and confirm the submission.", fields: [{key:"consent",label:"Confirmations",type:"consent",required:true}]}
] as const;

export const consentStatements = [
  "I confirm that the information provided is accurate to the best of my knowledge.",
  "I understand that this assessment does not create a binding contract.",
  "I understand that Nuvrixa may use this information to prepare a proposed solution, process map, recommendation or prototype.",
  "I understand that any estimated scope or pricing will only be confirmed after review.",
  "I confirm that I am authorised to submit information on behalf of the business.",
  "I agree to the Nuvrixa Privacy Policy.",
  "I agree to be contacted regarding this enquiry."
] as const;

export function requiredKeysForSection(section: DiscoverySection) {
  return section.fields.filter((field) => field.required).map((field) => field.key);
}
