/* eslint-disable @next/next/no-html-link-for-pages */
import styles from "./solutions.module.css";
import { BrandLogo } from "@/components/brand/brand-logo";

const solutions = [
  {icon:"♙⌑",title:"1. AI Lead Management & Sales System",desc:"Capture, qualify and convert more leads with intelligent automation.",chaos:["Leads lost in emails & chats","No follow-ups","Manual data entry","Low conversion rates"],fix:["Automated lead capture","AI lead qualification","Follow-ups & reminders","Pipeline & performance reports"]},
  {icon:"◔",title:"2. WhatsApp Customer Service System",desc:"Automate enquiries, bookings and support on WhatsApp.",chaos:["Slow replies","Missed messages","No enquiry tracking","Customers get frustrated"],fix:["Instant AI responses","Enquiry routing","Booking & reminders","CRM & ticket sync"]},
  {icon:"♬",title:"3. AI Support & Ticketing System",desc:"Smart ticketing and support management for faster resolutions.",chaos:["Tickets lost or ignored","No prioritisation","Long resolution times","No performance tracking"],fix:["Ticket creation & routing","SLA tracking & escalation","AI suggestions","Knowledge base integration"]},
  {icon:"▣",title:"4. Client Portal Solutions",desc:"Secure portals for clients to track projects, documents and requests.",chaos:["Clients always asking for updates","Documents everywhere","No transparency","Time wasted on admin"],fix:["Project progress tracking","Document sharing","Invoices & payments","Support tickets & messages"]},
  {icon:"◇",title:"5. Internal Operations Platform",desc:"One central system to run your business operations seamlessly.",chaos:["Disconnected tools","Data scattered","No visibility","Inefficient operations"],fix:["All-in-one platform","Real-time dashboards","Task & team management","Operational visibility"]},
  {icon:"▤",title:"6. Document Processing Automation",desc:"Extract, validate and process documents with AI.",chaos:["Manual data entry","Errors & inaccuracies","Slow approvals","Documents hard to find"],fix:["Data extraction (AI/OCR)","Auto classification","Validation & routing","Digital organisation"]},
  {icon:"$",title:"7. Invoice & Payment Automation",desc:"Automate quotes, invoices, payments and collections.",chaos:["Late payments","Manual invoicing","Payment tracking pain","Cash flow issues"],fix:["Automated invoicing","Payment reminders","Reconciliation","Cash flow reporting"]},
  {icon:"✺",title:"8. AI Knowledge Base & Assistant",desc:"Secure AI assistant trained on your documents and processes.",chaos:["Staff can’t find information","Repeated questions","Onboarding takes time","Knowledge stays in silos"],fix:["Smart search","Instant answers","Source citations","Role-based access"]},
];
const industries=[["▥","Property","Management"],["▣","Professional","Services"],["⌕","Field","Services"],["◇","Training","Providers"],["♡","NGOs &","Community"],["♜","Contractors",""],["🛒","Retail","Operations"],["⚙","Service","Businesses"]];

function Logo(){return <BrandLogo className={styles.logo}/>}
function List({items,type}:{items:string[];type:"bad"|"good"}){return <ul className={type=== "bad"?styles.bad:styles.good}>{items.map(x=><li key={x}>{type==="bad"?"⊗":"✓"}<span>{x}</span></li>)}</ul>}
function SolutionCard({item}:{item:typeof solutions[number]}){return <article className={styles.card}><div className={styles.cardTop}><div className={styles.cardIcon}>{item.icon}</div><div><h3>{item.title}</h3><p>{item.desc}</p></div></div><div className={styles.cardSection}><b>CHAOS</b><List items={item.chaos} type="bad"/></div><div className={styles.arrow}>↓</div><div className={styles.cardSection}><b className={styles.fixTitle}>SOLUTION</b><List items={item.fix} type="good"/></div></article>}
function HeroDiagram(){return <div className={styles.diagram} aria-label="Chaos transformed into automated business systems"><div className={styles.network}>{["✉","▣","▤","▥","◔","♙"].map((x,i)=><i style={{"--i":i} as React.CSSProperties} key={i}>{x}</i>)}</div><div className={styles.chaosBox}><b>THE CHAOS</b>{["Manual & Repetitive Work","Disconnected Systems","Lost Leads & Opportunities","Slow Response Times","Human Errors","No Real-Time Visibility","Unhappy Customers","Wasted Time & Money"].map(x=><span key={x}>⊗　{x}</span>)}</div><div className={styles.chevrons}>»</div><div className={styles.dashboard}><div className={styles.dashHead}><Logo/><span>◉　◉　◉</span></div><div className={styles.dashBody}><aside>{["Dashboard","Automations","Leads","Clients","Reports"].map(x=><span key={x}>{x}</span>)}</aside><main><div className={styles.miniCards}><i/><i/><i/></div><div className={styles.lineChart}>⌁⌁⌁</div><div className={styles.dashBottom}><i>◔</i><i>◇⌁◇</i></div></main></div></div><div className={styles.platform}><i/><i/><i/><i/></div><div className={styles.solutionBox}><b>THE SOLUTION</b>{["Automated Workflows","Integrated Systems","Captured & Qualified Leads","Faster Responses","Reduced Errors","Real-Time Insights","Happier Customers","More Time & Higher Profits"].map(x=><span key={x}>✓　{x}</span>)}</div></div>}

export default function SolutionsPage(){return <main className={styles.page}>
  <header className={styles.header}><a href="/"><Logo/></a><nav>{["Home","Solutions","Services","Process","Results"].map(x=><a className={x==="Solutions"?styles.active:""} href={x==="Home"?"/":`/${x.toLowerCase()}`} key={x}>{x}</a>)}</nav><a className={styles.audit} href="#audit">Book Free Automation Audit　→</a></header>
  <section className={styles.hero}><div className={styles.copy}><span>SOLUTIONS</span><h1>From Chaos To Clarity.<br/><em>We Build The Systems.</em></h1><p>Outdated processes, disconnected tools and manual work slow you down. We design AI-powered systems and automations that fix the chaos and help your business grow.</p></div><HeroDiagram/></section>
  <section className={styles.solutions}><div className={styles.heading}><span>Our Solutions</span><h2>Powerful Systems For Modern Businesses</h2><p>Solutions designed to eliminate friction, automate operations and drive real results.</p></div><div className={styles.grid}>{solutions.map(x=><SolutionCard item={x} key={x.title}/>)}</div></section>
  <section className={styles.industries}><h2>Designed For Businesses That Want To Move Forward</h2><div>{industries.map(([icon,a,b])=><article key={a}><i>{icon}</i><p>{a}<br/>{b}</p></article>)}</div><small>ⓘ　Outcomes depend on your business, current processes, implementation scope and system usage.</small></section>
  <section className={styles.cta} id="audit"><div className={styles.calendar}><div/><i>◷</i></div><div><h2>Ready To Turn <span>Chaos</span> Into <em>Clarity?</em></h2><p>Book your free 30-minute Automation Discovery Session and let us show you how Nuvrixa can help you work smarter, reduce costs and scale with confidence.</p><small>✓　30 Minutes　　✓　100% Free　　✓　No Obligation　　✓　Built Around Your Business</small></div><div><a className={styles.audit} href="/audit">Book My Free 30-Minute Audit　→</a><p>No credit card required.</p></div></section>
 </main>}
