"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useState } from "react";
import styles from "./faq.module.css";
import { BrandLogo } from "@/components/brand/brand-logo";
const faqs=[
 {category:"General",question:"What is Nuvrixa?",answer:"Nuvrixa designs and builds AI-powered business systems that reduce manual work, connect disconnected tools and give teams clearer operational visibility. Every solution is tailored to the client’s processes, goals and growth plans."},
 {category:"General",question:"What types of businesses do you work with?",answer:"We work with growing organisations across professional services, property management, field services, training, NGOs, contracting, retail and other service-based industries. We assess each business individually rather than applying a one-size-fits-all system."},
 {category:"General",question:"What business problems can Nuvrixa solve?",answer:"Typical challenges include repetitive administration, missed follow-ups, disconnected systems, slow quotations, manual reporting, scattered documents, inconsistent customer communication and limited visibility across operations."},
 {category:"General",question:"Do you only work with large companies?",answer:"No. We work with small and growing businesses as well as established teams. The important factors are the business problem, expected impact, available data and whether automation is a practical fit for the operation."},
 {category:"General",question:"Can you improve an existing system instead of replacing it?",answer:"Yes. We first assess what already works. Where practical, we improve, connect or automate existing tools instead of forcing an unnecessary replacement. A new platform is recommended only when it creates a clear operational benefit."},

 {category:"AI & Automation",question:"What are the benefits of AI automation?",answer:"AI automation can reduce repetitive administration, improve response times, connect disconnected tools, increase operational visibility, reduce avoidable errors and create more consistent customer experiences."},
 {category:"AI & Automation",question:"What business tasks can be automated?",answer:"Common examples include lead capture, follow-ups, appointment booking, quotation and invoice generation, document processing, customer support, onboarding, approvals, reminders, reporting and moving data between business systems."},
 {category:"AI & Automation",question:"Will AI replace our employees?",answer:"Our goal is to remove repetitive work and help employees make faster, better-informed decisions. Important approvals and sensitive decisions can remain with people, while automation handles predictable tasks and information flow."},
 {category:"AI & Automation",question:"Can AI work with our company documents and knowledge?",answer:"Yes. We can build controlled assistants that search approved policies, procedures, product information and internal documents. Access can be restricted by role, and the system can be designed to cite its information sources."},
 {category:"AI & Automation",question:"How do you decide where automation will have the greatest impact?",answer:"We examine task frequency, time spent, error rates, delays, customer impact and implementation effort. We then prioritise opportunities that offer practical value while keeping risk and complexity manageable."},

 {category:"Services",question:"How do you ensure the solution fits our business?",answer:"Every engagement begins with discovery and process mapping. We learn how your team works, document requirements and design the solution around your existing operations, priorities, tools and growth plans."},
 {category:"Services",question:"What services does Nuvrixa provide?",answer:"Our services include AI and automation strategy, workflow automation, system integration, custom AI solutions, data and reporting systems, AI assistants and chatbots, cloud infrastructure, client portals and ongoing optimisation."},
 {category:"Services",question:"Can you build a client portal or internal operations platform?",answer:"Yes. We can build secure portals and internal systems for project tracking, document sharing, requests, approvals, dashboards, customer communication and other workflows specific to your business."},
 {category:"Services",question:"Do you provide process mapping and consulting before development?",answer:"Yes. We document the current process, identify bottlenecks and define the future workflow before building. This reduces uncertainty and ensures the proposed technology solves the right operational problem."},
 {category:"Services",question:"Can you automate document-heavy processes?",answer:"Yes. Solutions may capture information from forms and documents, classify files, route approvals, generate standard documents, extract data and store records in the correct system with appropriate human review."},

 {category:"Pricing & Projects",question:"How much does a Nuvrixa project cost?",answer:"Pricing depends on workflow complexity, integrations, data requirements, security needs and the level of custom development. Current project budget options begin at $1,500 USD, and you receive a clear scope and price before work starts."},
 {category:"Pricing & Projects",question:"How long does it take to build an automation solution?",answer:"Timelines depend on scope and complexity. A focused workflow may take a few weeks, while a connected multi-system platform may take several months. You receive a clear delivery plan before work begins."},
 {category:"Pricing & Projects",question:"Do you offer fixed-price projects or monthly services?",answer:"The commercial structure depends on the engagement. A defined build may use milestone-based pricing, while monitoring, maintenance and continuous optimisation may be provided through an ongoing service agreement."},
 {category:"Pricing & Projects",question:"What is included in a project proposal?",answer:"A proposal normally defines the business problem, recommended solution, scope, deliverables, implementation stages, assumptions, client responsibilities, timeline, price and available support options."},
 {category:"Pricing & Projects",question:"Can a project be delivered in phases?",answer:"Yes. We often start with the highest-impact workflow or a focused prototype, validate the result and then expand. Phased delivery can reduce risk, produce value earlier and make larger transformations easier to manage."},

 {category:"Security & Privacy",question:"Is our data safe and secure?",answer:"Security and privacy are built into our process. We use appropriate access controls, secure integrations, encrypted services and reputable platforms, while limiting data access to what each solution requires."},
 {category:"Security & Privacy",question:"Who can access our business information?",answer:"Access is limited to authorised people and systems required for delivery and support. Solutions can include role-based permissions so employees only see the information needed for their responsibilities."},
 {category:"Security & Privacy",question:"Do you use our private data to train public AI models?",answer:"We design integrations to use approved data for the agreed business purpose. The exact data handling depends on the selected provider, so we document the relevant configuration and avoid unnecessary sharing of confidential information."},
 {category:"Security & Privacy",question:"Can sensitive actions require human approval?",answer:"Yes. Payments, record changes, customer commitments, legal decisions and other sensitive actions can be placed behind approval steps. AI can prepare or recommend an action without being permitted to complete it automatically."},
 {category:"Security & Privacy",question:"What happens to our data if the project ends?",answer:"Data ownership, access handover, retention and deletion requirements are agreed for the project and the platforms involved. We help clients retain appropriate access to their systems and remove Nuvrixa access when it is no longer required."},

 {category:"Integrations",question:"What tools and technologies do you use?",answer:"We select technology based on the job. Our toolkit includes HubSpot, Cal.com, n8n, Make, Zapier, cloud platforms, databases, APIs and leading AI models, alongside custom-built applications when needed."},
 {category:"Integrations",question:"Can you connect tools that do not currently communicate?",answer:"Yes. We can use native integrations, APIs, webhooks or automation platforms to synchronise information and trigger actions between systems. We first confirm what each platform supports and identify any limitations."},
 {category:"Integrations",question:"Can you integrate with our CRM, email and calendar?",answer:"Yes. Depending on the platforms and available permissions, we can connect lead forms, CRM records, email notifications, appointment scheduling and calendars so information follows a consistent workflow."},
 {category:"Integrations",question:"What if our existing software does not have an API?",answer:"We assess alternative options such as exports, scheduled file processing, email-based workflows, approved browser automation or a replacement for the isolated component. The recommendation depends on reliability, security and maintenance risk."},
 {category:"Integrations",question:"Will the integration create duplicate customer records?",answer:"We design matching and update rules around stable identifiers such as email addresses, customer numbers or system IDs. Testing includes duplicate prevention, validation and clear handling for records that cannot be matched safely."},

 {category:"Support",question:"Do you offer ongoing support after project delivery?",answer:"Yes. We provide monitoring, optimisation, maintenance, training and ongoing support packages to keep your systems reliable, secure and aligned with the way your business evolves."},
 {category:"Support",question:"What happens if an automation stops working?",answer:"Supported systems can be monitored for failures and unusual behaviour. We investigate the cause, restore the workflow where possible and update the integration when a connected platform or business process has changed."},
 {category:"Support",question:"Will our team receive training?",answer:"Yes. Training is tailored to the people who use or manage the system. It may include live sessions, process guidance, administrative handover and documentation for common tasks and responsibilities."},
 {category:"Support",question:"Can you improve the system after it has launched?",answer:"Yes. We can review usage, feedback, errors and changing requirements, then refine workflows or add new capabilities. Continuous improvement is especially useful as teams, data and operational priorities evolve."},
 {category:"Support",question:"Can our own IT team manage the solution?",answer:"Where appropriate, we provide documentation, credentials handover, technical guidance and training so an internal team can operate the system. The exact handover depends on the platforms, licences and support arrangement."},

 {category:"Getting Started",question:"How do we get started?",answer:"Complete the business discovery form or book a free 30-minute Automation Audit. We review your needs, identify practical opportunities and recommend the next step based on your business and desired outcome."},
 {category:"Getting Started",question:"How does a 30-minute Automation Audit work?",answer:"We start with a focused conversation about your current processes, tools, challenges and goals. We identify high-impact automation opportunities and explain practical next steps, with no obligation to proceed."},
 {category:"Getting Started",question:"What should we prepare before the first meeting?",answer:"Bring examples of the process you want to improve, the systems involved, the people responsible, current delays or errors and the result you want. Sample forms, reports or screenshots can make the discussion more productive."},
 {category:"Getting Started",question:"What happens after the discovery form is submitted?",answer:"Your information is securely recorded in our CRM, and you are taken to the booking calendar. After you choose a time, we review the discovery brief so the first meeting can focus on priorities, possible solutions and next steps."},
 {category:"Getting Started",question:"Do we need to know exactly what technology we want?",answer:"No. You only need to explain the business problem, current workflow and desired result. Nuvrixa evaluates suitable tools and recommends an approach based on value, usability, security and maintainability."},
] as const;
const categoryIcons={"General":"▰","AI & Automation":"♙","Services":"◇","Pricing & Projects":"$","Security & Privacy":"♢","Integrations":"↗","Support":"♬","Getting Started":"♢"} as const;
const categories=Object.keys(categoryIcons) as Array<keyof typeof categoryIcons>;
function Logo(){return <BrandLogo className={styles.logo}/>}
function HeroArt(){return <div className={styles.heroArt}><div className={styles.circuit}/><div className={styles.bubble}>FAQ<small>― ••• ―</small></div><div className={styles.rings}/>{[["?",8,10],["♙",-45,95],["⚙",320,40],["▥",350,125]].map(([x,l,t])=><i style={{left:l,top:t}} key={String(x)}>{x}</i>)}</div>}
export default function FaqPage(){const[q,setQ]=useState("");const[category,setCategory]=useState<(typeof categories)[number]>("General");const visible=faqs.filter(x=>(!q?x.category===category:true)&&`${x.question} ${x.answer}`.toLowerCase().includes(q.toLowerCase()));return <main className={styles.page}>
 <header className={styles.header}><a href="/"><Logo/></a><nav>{["Home","Solutions","Services","Process","Results","FAQ"].map(x=><a className={x==="FAQ"?styles.active:""} href={x==="Home"?"/":`/${x.toLowerCase()}`} key={x}>{x}</a>)}</nav><a className={styles.audit} href="/audit">Book Free 30-Minute Audit →</a></header>
 <section className={styles.hero}><div><span>FAQ</span><h1>Frequently Asked<br/><em>Questions</em></h1><p>Find answers to common questions about<br/>Nuvrixa, our services and how we work.</p><label className={styles.search}>⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search our knowledge base..."/></label></div><HeroArt/></section>
 <section className={styles.content}><aside><h2>CATEGORIES</h2>{categories.map(x=><button type="button" aria-pressed={category===x} className={category===x?styles.selected:""} onClick={()=>{setCategory(x);setQ("")}} key={x}><i>{categoryIcons[x]}</i><span>{x}</span><b>{faqs.filter(f=>f.category===x).length}</b></button>)}<div className={styles.help}><i>♧</i><h3>Can’t find what you’re<br/>looking for?</h3><p>We’re here to help you.</p><a href="/contact">Contact us →</a></div></aside><div className={styles.questions} aria-live="polite">{visible.map((x,i)=><details open={i===0} key={x.question}><summary><i>{i+1}</i><h2>{x.question}</h2><b>⌄</b></summary><p>{x.answer}</p></details>)}{visible.length===0&&<p className={styles.empty}>No matching questions found. Try another search.</p>}</div></section>
 <section className={styles.cta}><div className={styles.calendar}><div/><i>◷</i></div><div><span>STILL HAVE QUESTIONS?</span><h2>Let’s Talk About Your <em>Automation Goals.</em></h2><p>Book your free 30-minute Automation Audit and get personalised insights on how we can help your business save time, reduce costs and scale.</p><small>✓ 30 Minutes  ✓ 100% Free  ✓ No Obligation  ✓ Actionable Insights</small></div><div><a className={styles.audit} href="/audit">Book My Free 30-Minute Audit →</a><p>No credit card required.</p></div></section>
 </main>}
