"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useState } from "react";
import styles from "./faq.module.css";
import { BrandLogo } from "@/components/brand/brand-logo";
const faqs=[
 {category:"General",question:"What is Nuvrixa?",answer:"Nuvrixa is an AI automation agency that helps businesses eliminate manual work, streamline operations and build intelligent systems that drive measurable results. We design, build and optimise custom solutions tailored to your unique business needs."},
 {category:"Getting Started",question:"How does a 30-minute Automation Audit work?",answer:"We start with a focused conversation about your current processes, tools, challenges and goals. We identify high-impact automation opportunities and explain the practical next steps, with no obligation to proceed."},
 {category:"General",question:"What types of businesses do you work with?",answer:"We work with growing organisations across professional services, property management, field services, training, NGOs, contracting, retail and other service-based industries. Our systems are tailored to each business."},
 {category:"AI & Automation",question:"What are the benefits of AI automation?",answer:"AI automation can reduce repetitive administration, improve response times, connect disconnected tools, increase operational visibility, reduce avoidable errors and create more consistent customer experiences."},
 {category:"Services",question:"How do you ensure the solutions fit our business?",answer:"Every engagement begins with discovery and process mapping. We learn how your team works, document requirements and design the solution around your existing operations, priorities, tools and growth plans."},
 {category:"Pricing & Projects",question:"How long does it take to build an automation solution?",answer:"Timelines depend on scope and complexity. A focused workflow may take a few weeks, while a connected multi-system platform may take several months. You receive a clear delivery plan before work begins."},
 {category:"Support",question:"Do you offer ongoing support after project delivery?",answer:"Yes. We provide monitoring, optimisation, maintenance, training and ongoing support packages to keep your systems reliable, secure and aligned with the way your business evolves."},
 {category:"Integrations",question:"What tools and technologies do you use?",answer:"We select technology based on the job. Our toolkit includes HubSpot, Cal.com, n8n, Make, Zapier, cloud platforms, databases, APIs and leading AI models, alongside custom-built applications when needed."},
 {category:"Security & Privacy",question:"Is our data safe and secure?",answer:"Security and privacy are built into our process. We use appropriate access controls, secure integrations, encrypted services and reputable platforms, while limiting data access to what each solution requires."},
 {category:"Getting Started",question:"How do we get started?",answer:"Book a free 30-minute Automation Audit. Tell us about your business and select a convenient time. We will review your needs, identify opportunities and recommend a practical path forward."},
] as const;
const categoryIcons={"General":"▰","AI & Automation":"♙","Services":"◇","Pricing & Projects":"$","Security & Privacy":"♢","Integrations":"↗","Support":"♬","Getting Started":"♢"} as const;
const categories=Object.keys(categoryIcons) as Array<keyof typeof categoryIcons>;
function Logo(){return <BrandLogo className={styles.logo}/>}
function HeroArt(){return <div className={styles.heroArt}><div className={styles.circuit}/><div className={styles.bubble}>FAQ<small>― ••• ―</small></div><div className={styles.rings}/>{[["?",8,10],["♙",-45,95],["⚙",320,40],["▥",350,125]].map(([x,l,t])=><i style={{left:l,top:t}} key={String(x)}>{x}</i>)}</div>}
export default function FaqPage(){const[q,setQ]=useState("");const[category,setCategory]=useState<(typeof categories)[number]>("General");const visible=faqs.filter(x=>(!q?x.category===category:true)&&`${x.question} ${x.answer}`.toLowerCase().includes(q.toLowerCase()));return <main className={styles.page}>
 <header className={styles.header}><a href="/"><Logo/></a><nav>{["Home","Solutions","Services","Process","Results","FAQ"].map(x=><a className={x==="FAQ"?styles.active:""} href={x==="Home"?"/":`/${x.toLowerCase()}`} key={x}>{x}</a>)}</nav><a className={styles.audit} href="/audit">Book Free 30-Minute Audit　→</a></header>
 <section className={styles.hero}><div><span>FAQ</span><h1>Frequently Asked<br/><em>Questions</em></h1><p>Find answers to common questions about<br/>Nuvrixa, our services and how we work.</p><label className={styles.search}>⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search our knowledge base..."/></label></div><HeroArt/></section>
 <section className={styles.content}><aside><h2>CATEGORIES</h2>{categories.map(x=><button type="button" aria-pressed={category===x} className={category===x?styles.selected:""} onClick={()=>{setCategory(x);setQ("")}} key={x}><i>{categoryIcons[x]}</i><span>{x}</span><b>{faqs.filter(f=>f.category===x).length}</b></button>)}<div className={styles.help}><i>♧</i><h3>Can’t find what you’re<br/>looking for?</h3><p>We’re here to help you.</p><a href="/contact">Contact us　→</a></div></aside><div className={styles.questions} aria-live="polite">{visible.map((x,i)=><details open={i===0} key={x.question}><summary><i>{i+1}</i><h2>{x.question}</h2><b>⌄</b></summary><p>{x.answer}</p></details>)}{visible.length===0&&<p className={styles.empty}>No matching questions found. Try another search.</p>}</div></section>
 <section className={styles.cta}><div className={styles.calendar}><div/><i>◷</i></div><div><span>STILL HAVE QUESTIONS?</span><h2>Let’s Talk About Your <em>Automation Goals.</em></h2><p>Book your free 30-minute Automation Audit and get personalised insights on how we can help your business save time, reduce costs and scale.</p><small>✓　30 Minutes　　✓　100% Free　　✓　No Obligation　　✓　Actionable Insights</small></div><div><a className={styles.audit} href="/audit">Book My Free 30-Minute Audit　→</a><p>No credit card required.</p></div></section>
 <footer className={styles.footer}><div className={styles.footerGrid}><div><Logo/><p>AI-powered systems and automations that help businesses save time, reduce costs and scale with confidence.</p><div className={styles.social}>in　𝕏　✉</div></div><div><h3>SOLUTIONS</h3>{["Solutions","Chaos","Blueprint","Integrations","Portal"].map(x=><a href="/solutions" key={x}>{x}</a>)}</div><div><h3>COMPANY</h3>{["Process","Results","Services","Contact"].map(x=><a href={`/${x.toLowerCase()}`} key={x}>{x}</a>)}</div><div><h3>RESOURCES</h3><a href="/faq">FAQ</a><a href="/privacy-policy">Privacy Policy</a><a href="/terms">Terms & Conditions</a></div><div><h3>STAY UPDATED</h3><p>Get insights on AI, automation and business transformation.</p><form><label htmlFor="faq-email">Email</label><input id="faq-email" type="email" placeholder="Enter your email"/><button aria-label="Subscribe">→</button></form></div></div><div className={styles.bottom}><span>© 2025 Nuvrixa. All rights reserved.</span><span><a href="/privacy-policy">Privacy Policy</a>　 |　 <a href="/terms">Terms & Conditions</a></span><a href="mailto:hello@nuvrixa.co.za">hello@nuvrixa.co.za</a></div></footer>
 </main>}
